### ISSUE TITLE
Needs a cooler name

### ISSUE THREAD

**Issue by justinwoo** [justinwoo/spacchetti#2]

**Comment by bitemyapp** [comment]
![screenshot from 2018-06-13 18-07-13](https://user-images.githubusercontent.com/320177/41383076-9ac8f6f4-6f34-11e8-9222-4a253585c88d.png)

**Comment by bitemyapp** [comment]
![screenshot from 2018-06-13 18-07-35](https://user-images.githubusercontent.com/320177/41383090-a895870c-6f34-11e8-9169-8d9cd2e936c3.png)

**Comment by chexxor** [comment]
![crop-640x360-000](https://user-images.githubusercontent.com/843161/41383212-39f97136-6f35-11e8-893b-31cf55aff0cd.jpg)

**Comment by justinwoo** [comment]
These are horrible omfgggggg

**Comment by f-f** [comment]
🍝

**Comment by justinwoo** [comment]
Fixed~
