### ISSUE TITLE
Example Nix usage using package set information from this repo

### ISSUE THREAD

**Issue by justinwoo** [justinwoo/spacchetti#3]
I'd really like to see how generation of some NIx (through https://github.com/dhall-lang/dhall-nix) for installing dependencies. I hope it can be not very difficult for someone who knows Nix already.

as said on https://twitter.com/jusrin00/status/1009409407090819072

**Comment by justinwoo** [comment]
I don't think any real movement has happened on this, other than that I know enough Perl now to make this happen and generate some nix expressions. My biggest issue with this would just be that it's really damn slow to generate the derivations the first time around to the point that I might as well make a separate "psc-package2nix" project. So I will close this as I have something actually actionable for myself, and there exists some Haskell scripts in this repo now that start to get at the problem if people are interested enough in it.

**Comment by Profpatsch** [comment]
Well, I do have a PR ready, just haven’t gotten around to pushing it.
