### ISSUE TITLE
Question: lack of newline characters in generated file via `local-setup`

### ISSUE THREAD

**Issue by JordanMartinez** [justinwoo/spacchetti#31]
When I use `spacchetti local-setup`, it generates the following file automatically...
```
let mkPackage = {- normal stuff -} in let upstream = {- upstream dhall stuff -} in upstream
```
...rather than something that can be easily edited as all the examples in the docs show:
```
   let mkPackage = -- normal stuff
in let upstream = -- upstream dhall stuff
in upstream
```
Is this due to wanting the code to work regardless of which OS' newline characters are being used? Could this be changed to generate something more like the second example above rather than the first?

**Comment by justinwoo** [comment]
oh, if this is from one of the newer versions, it's just how `dhall format` normally formats these. This could probably be changed to outputting a string without running format afterwards.

**Comment by justinwoo** [comment]
I tried this with 0.3.0.0, this is my result:

```haskell
    let mkPackage =
          https://raw.githubusercontent.com/justinwoo/spacchetti/140918/src/mkPackage.dhall

in  let upstream =
          https://raw.githubusercontent.com/justinwoo/spacchetti/140918/src/packages.dhall

in  upstream
```

**Comment by JordanMartinez** [comment]
This might also be because I didn't get Dhall fully installed on my system. (I tried `stack build dhall` and there was some library not installed on my computer or something...?) However, I got `spacchetti-cli` to work by downloading `dhall-to-json`. So, this might also be because my environment isn't fully set up yet.

**Comment by justinwoo** [comment]
Yeah, I'm not entirely sure what the easiest way to install `dhall` and others would be. I use `nix-env -f easy-purescript.nix -i` (https://github.com/justinwoo/easy-purescript-nix/) now but downloaded the binary or built the cloned repo before.

**Comment by f-f** [comment]
We build static binaries for all `dhall` and `dhall-json` releases, so you can just download a binary from [the release page](https://github.com/dhall-lang/dhall-haskell/releases/tag/1.18.0) and put it in your path

**Comment by justinwoo** [comment]
Can we consider this fixed?

**Comment by JordanMartinez** [comment]
I forgot to respond to this. Yes, I believe so.

**Comment by justinwoo** [comment]
Thanks!
