### ISSUE TITLE
Couldn't find node.js

### ISSUE THREAD

**Issue by 573** [justinwoo/spacchetti#46]
Assuming:
> cat psc-package.json
{
    "set": "local",
    "depends": [
        "prelude",
        "psci-support",
        "lists",
    ],
    "name": "psc-getting-started",
    "source": ""
}

> psc-package repl

I am getting:
> import Prelude
> import Data.List
> range 0 999
Couldn't find node.js

**Comment by garyb** [comment]
Do you have node installed somewhere globally? The REPL looks for a `nodejs` or `node` executable on the PATH and if it fails that's the message you'll get.

**Comment by 573** [comment]
Obvs I assumed easy-purescript-nix took care of that as well, my fault.
